CREATE DATABASE DB_PIZZARIA;
USE DB_PIZZARIA;

CREATE TABLE PRODUTOS(
ID BIGINT(5) AUTO_INCREMENT,
NOME_PRODUTO VARCHAR (255),
PRIMARY KEY (ID)
);

CREATE TABLE PIZZAS(
NOME VARCHAR (255) NOT NULL,
SABOR VARCHAR (255) NOT NULL,
INGREDIENTE VARCHAR (255) NOT NULL,
PRECO DECIMAL(6,2) NOT NULL,
CATEGORIA_ID BIGINT,
FOREIGN KEY (CATEGORIA_ID) REFERENCES PRODUTOS(ID) 
); 

INSERT INTO PRODUTOS (NOME_PRODUTO) VALUES ("PIZZA");
INSERT INTO PRODUTOS (NOME_PRODUTO) VALUES ("PIZZA");
INSERT INTO PRODUTOS (NOME_PRODUTO) VALUES ("PIZZA");
INSERT INTO PRODUTOS (NOME_PRODUTO) VALUES ("PIZZA");
INSERT INTO PRODUTOS (NOME_PRODUTO) VALUES ("PIZZA");

SELECT*FROM PRODUTOS;

INSERT INTO PIZZAS(NOME,SABOR,INGREDIENTE,PRECO,CATEGORIA_ID) VALUES("ATUM","SALGADA","ATUM TEMPERADO, CEBOLA E PARMESÃO",40.00,1);
INSERT INTO PIZZAS(NOME,SABOR,INGREDIENTE,PRECO,CATEGORIA_ID) VALUES("BAURU","SALGADA","PRESUNTO, MUSSARELA E TOMATE",28.00,1);
INSERT INTO PIZZAS(NOME,SABOR,INGREDIENTE,PRECO,CATEGORIA_ID) VALUES("CAMARÃO","SALGADA","CAMARÃO MÉDIO, PARMESÃO E CEBOLAS",56.50,1);
INSERT INTO PIZZAS(NOME,SABOR,INGREDIENTE,PRECO,CATEGORIA_ID) VALUES("DA ONDA","SALGADA","FRANGO TEMPERADO, CATUPIRY E BATATA PALHA",43.00,1);
INSERT INTO PIZZAS(NOME,SABOR,INGREDIENTE,PRECO,CATEGORIA_ID) VALUES("ELMA CHIPS","SALGADA","MUSSARELA E BATATA PALHA",28.00,1);
INSERT INTO PIZZAS(NOME,SABOR,INGREDIENTE,PRECO,CATEGORIA_ID) VALUES("TORTUGUITA","DOCE","CHOCOLATE AO LEITE E BRANCO COM TORTUGUITA",48.00,1);

SELECT*FROM PIZZAS;

INSERT INTO PRODUTOS (NOME_PRODUTO) VALUES("BEIRUTE");

SELECT*FROM PIZZAS WHERE PRECO>45.00;
SELECT*FROM PIZZAS WHERE PRECO BETWEEN 50.00 AND 100.00;
SELECT*FROM PIZZAS WHERE NOME LIKE "D%"; -- BUSCA AS LETRAS INICIAIS

SELECT*FROM PIZZAS INNER JOIN PRODUTOS ON
PIZZAS.CATEGORIA_ID=PRODUTOS.ID;

SELECT NOME,PRECO FROM PIZZAS;

SELECT NOME,SABOR,PRECO FROM PIZZAS
LEFT JOIN PRODUTOS ON PRODUTOS.ID=PIZZAS.CATEGORIA_ID;



